- name: Fetch and copy file from GitHub to remote server
  hosts: all
  become: true

  tasks:
    - name: Clone repository
      git:
        repo: https://github.com/code-sourabh/ansible-poc.git
        dest: /home/aerospike-conf
        clone: yes
        update: yes
        
        
#         repo: https://github.com/code-sourabh/ansible-poc.git
#         dest: /tmp/repository
#       register: git_result

#     - name: Copy file to remote server
#       copy:
#         src: /tmp/repository/aerospike.conf
#         dest: /home/aerospike.conf
#       when: git_result.changed
